
services:
  frontend:
    build:
      context: ./allergy_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend
          target: "/usr/share/nginx/html"
          action: sync

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    develop:
      watch:
        - path: ./backend/src/
          target: "/home/appuser/app/src/"
          action: rebuild
        - path: ./backend/pyproject.toml
          target: "/home/appuser/app/pyproject.toml"
          action: rebuild
        - path: ./backend/requirements.txt
          target: "/home/appuser/app/requirements.txt"
          action: rebuild
        - path: ./backend/uv.lock
          target: "/home/appuser/app/uv.lock"
          action: rebuild
        - path: ./backend/Dockerfile
          action: rebuild
        - path: ./backend/.dockerignore
          action: rebuild
        
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
